nightswatcher: fix requirements
Add missing `packaging` dependency:
```
▸ make nightswatcher/test
2026-10-02 00:45:03+02:00 ▹ m nightswatcher/test
[2026-10-01 22:45:04 +0000] [1] [INFO] Starting gunicorn 26.2.0
[2026-10-01 22:45:04 +0000] [1] [INFO] Listening at: http://0.0.0.0:9742 (1)
[2026-10-01 22:45:04 +0000] [1] [INFO] Using worker: gevent
[2026-10-01 22:45:04 +0000] [7] [INFO] Booting worker with pid: 7
[2026-10-01 22:45:04 +0000] [1] [INFO] Control socket listening at /root/.gunicorn/gunicorn.ctl
[2026-10-01 22:45:04 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 753, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/ggevent.py", line 143, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 137, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 149, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 420, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nightswatcher/nightswatcher.py", line 495, in <module>
    testing()
  File "/nightswatcher/nightswatcher.py", line 474, in testing
    raise ValueError(f'bad version string: {version}')
ValueError: bad version string: req_body
bad version string: req_body
[2026-10-01 22:45:04 +0000] [7] [INFO] Worker exiting (pid: 7)
2026-10-01 22:45:04,288 root INFO     Fetch build worker waiting for new builds....
[2026-10-01 22:45:04 +0000] [1] [ERROR] Worker (pid:7) exited with code 3.
[2026-10-01 22:45:04 +0000] [1] [ERROR] Shutting down: Master
[2026-10-01 22:45:04 +0000] [1] [ERROR] Reason: Worker failed to boot.
make: *** [nightswatcher/settings.mk:31: nightswatcher/test] Error 3
```