nightswatcher: use resp.text instead of no longer supported resp.body
```
  File "falcon/app.py", line 440, in falcon.app.App.__call__
  File "/nightswatcher.py", line 299, in on_post
    resp.body = '["ok"]'
    ^^^^^^^^^
  File "falcon/response.py", line 221, in falcon.response.Response.body
falcon.util.deprecation.AttributeRemovedError: The body attribute is no longer supported. Please use the text attribute instead.
```